name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16

        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :ares-fabric-1.16:build

      - uses: actions/upload-artifact@v2
        with:
          name: Ares
          path: build/*.jar

      - name: Cleanup Gradle Cache
        run: rm -rf ~/.gradle/caches/
